import type { Metadata } from 'next';
import './globals.css';
import styles from './Home.module.css';
import { ReactNode } from 'react';
export const metadata: Metadata = {
  title: 'React Premature Optimization',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => (
  <html lang="en">
    <body>
      <div className={styles.container}>
        <main className={styles.main}>{children}</main>
        <footer className={styles.footer} />
      </div>
    </body>
  </html>
);
export default RootLayout;
